### PR TITLE
Upgrade ruby to 2.5.5

### PR DESCRIPTION
**Pull request by colemanja91**

### CODE REVIEW

**Comment by colemanja91** [comment]
Brainy deploys fail with this update - looks like the lockfile is expecting an exact version match: https://gist.github.com/firstops/ff7522eada955df6b06a146eacb134f8

Rolling back until we figure that out

**Comment by colemanja91** [comment]
@rsanheim the issue on this one is that heaven installs the dev + heaven dependencies from the gemfile locally (so it can actually deploy). That step is failing because the Ruby version in the image does not match the Ruby version in the lockfile.

**Comment by rsanheim** [comment]
[ch2944]

**Comment by rsanheim** [comment]
[ch2944]

**Pull request merged**
